// <auto-generated />
using System;
using ConsoleApp1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(WorkContext))]
    [Migration("20210827134158_MigrationWithTph2")]
    partial class MigrationWithTph2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleApp1.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastModification")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Wage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Worker");
                });

            modelBuilder.Entity("ConsoleApp1.Cook", b =>
                {
                    b.HasBaseType("ConsoleApp1.Worker");

                    b.Property<string>("SpecialFood")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Cook");
                });

            modelBuilder.Entity("ConsoleApp1.Driver", b =>
                {
                    b.HasBaseType("ConsoleApp1.Worker");

                    b.Property<int>("NumberOfKm")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Driver");
                });
#pragma warning restore 612, 618
        }
    }
}
